
-- KOPIERA IN I POSTGRESQL
--SKAPAR ALLA TABELLER SOM VI HAR ATM


CREATE TABLE subscriptions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    playlist_limit INTEGER NOT NULL,
    early_access BOOLEAN NOT NULL
);

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    subscription_id INTEGER,
    role VARCHAR(50) NOT NULL DEFAULT 'customer',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (subscription_id)
        REFERENCES subscriptions(id)
);


CREATE TABLE songs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	artist VARCHAR(150) NOT NULL,
    title VARCHAR(150) NOT NULL,
    album VARCHAR(150),
    duration INTEGER NOT NULL,
    audio_url TEXT,
    image_url TEXT,
    release_type VARCHAR(20) NOT NULL DEFAULT 'released',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE playlists (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    user_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);


CREATE TABLE playlist_songs (
    playlist_id INTEGER NOT NULL,
    song_id INTEGER NOT NULL,

    PRIMARY KEY (playlist_id, song_id),

    FOREIGN KEY (playlist_id)
        REFERENCES playlists(id)
        ON DELETE CASCADE,

    FOREIGN KEY (song_id)
        REFERENCES songs(id)
        ON DELETE CASCADE
);


CREATE TABLE receipts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    subscription_id INTEGER NOT NULL,
    amount NUMERIC(10,2) NOT NULL,
    payment_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id)
        REFERENCES users(id),

    FOREIGN KEY (subscription_id)
        REFERENCES subscriptions(id)
);


CREATE TABLE content_pages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    content TEXT NOT NULL,
    required_subscription_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (required_subscription_id)
        REFERENCES subscriptions(id)
);

INSERT INTO subscriptions (name, playlist_limit, early_access)
VALUES
    ('Basic', 0, FALSE),
    ('Plus', 5, FALSE),
    ('Premium', 10, TRUE);